# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Terraform
  displayName: Setup Terraform
  jobs:
  - job: Init
    displayName: Terraform Init
    steps:
    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'Free Trial(2ee6da9b-a647-401e-9408-ab64ec71fb25)'
        backendAzureRmResourceGroupName: 'k8sdemorg'
        backendAzureRmStorageAccountName: 'k8sterraformstorage'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'YR36wPTgTmPH+ouRGN4cGskzPtbr5Y47RlMdSeKtceHuS3jo9SYfV2NeMJnQXu8wvusEC9tsohsQ+5e2jnxNMQ=='
    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: 'plan'
        commandOptions: '-out tfplan'
        environmentServiceNameAzureRM: 'Free Trial(2ee6da9b-a647-401e-9408-ab64ec71fb25)'
    - task: TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: 'tfplan'
        environmentServiceNameAzureRM: 'Free Trial(2ee6da9b-a647-401e-9408-ab64ec71fb25)'
